#!/usr/bin/env bash
#SBATCH --cpus-per-task=24
#SBATCH --gpus=0
#SBATCH --mem=16G
#SBATCH --time=23:00:00
#SBATCH --nodes=1
# #SBATCH --constraint="GPUMEM80GB|GPUMEM32GB"
#SBATCH --array=1-14
#SBATCH --output=log/outUltraBones100kCUDA_%a.out

module load apptainer
export PYTHONNOUSERSITE=1

apptainer exec --nv \
  --env PYTHONNOUSERSITE=1 \
  --env LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/opt/conda/lib \
  nirr_latest.sif \
  python mainUltraBones100k.py --target_specimen_id $SLURM_ARRAY_TASK_ID